before:
  hooks:
    - env GO111MODULE=on go test ./...
builds:
  - 
    env:
      - GO111MODULE=on
    main: cmd/booster/main.go
    binary: booster
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - 386
      - arm
    goarm:
      - 6
      - 7
    ldflags: -s -w -X main.version=v{{.Version}} -X main.commit={{.ShortCommit}} -X main.buildTime={{.Date}}
  - 
    env:
      - GO111MODULE=on
    main: cmd/daemon/main.go
    binary: daemon
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - 386
      - arm
    goarm:
      - 6
      - 7
    ldflags: -s -w -X main.version=v{{.Version}} -X main.commit={{.ShortCommit}} -X main.buildTime={{.Date}}

sign:
  artifacts: checksum

snapshot:
  name_template: "SNAPSHOT-{{ .ShortCommit }}"

snapcraft:
  publish: false

  # Single-line elevator pitch for your amazing snap.
  # 79 char long at most.
  summary: Strategy-based network interface balancer.

  # This the description of your snap. You have a paragraph or two to tell the
  # most important story about your snap. Keep it under 100 words though,
  # we live in tweetspace and your description wants to look good in the snap
  # store.
  description: |
    When **booster** spawns, it identifies the network interfaces available in the system that provide an active internet connection. It then starts a proxy server that speaks either **socks5** or **http**. According to some particular **strategy**, the server is able to **distribute** the incoming network traffic across the network interfaces collected.
    Source code is located at https://github.com/booster-proj/booster.

  grade: stable
  confinement: strict

  apps:
    daemon:
      plugs: [network, network-bind]
      daemon: simple
      
