before:
  hooks:
    - env GO111MODULE=on go test ./...
builds:
  - 
    env:
      - GO111MODULE=on
    main: cmd/booster/main.go
    binary: booster
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - 386
      - arm
      - arm64
    goarm:
      - 6
      - 7
    ldflags: -s -w -X main.version=v{{.Version}} -X main.commit={{.ShortCommit}} -X main.buildTime={{.Date}}

sign:
  artifacts: checksum

snapshot:
  name_template: "SNAPSHOT-{{ .Commit }}"
